new bin files.

diff --git a/.local/bin/get_env b/.local/bin/get_env
--- a/.local/bin/get_env
+++ b/.local/bin/get_env
@@ -1,4 +1,13 @@
 #!/bin/bash
 
-cmd="kwallet-query -f ENV_VARIABLES kdewallet -r unipr_usr 2>/dev/null"
-echo $(kwallet-query -f ENV_VARIABLES kdewallet -r $1 2>/dev/null)
+get_env() {
+    local env_var=$1
+    local env_value=$(kwallet-query -f ENV_VARIABLES kdewallet -r $env_var 2>/dev/null)
+    if [ -z "$env_value" ]; then
+        echo "Error: Environment variable $env_var not found in kwallet."
+        exit 1
+    fi
+    echo $env_value
+}
+
+get_env "$@"
